export const IMG = {
  intro1: require("./images/intro1.png"),
  intro2: require("./images/intro2.png"),
  intro3: require("./images/intro3.png"),
  defaultAv: require("./images/default-icon.png"),
  beachImg: require("./images/beach.png"),
  entertainmentImg: require("./images/entertainment.png"),
  foodImg: require("./images/food.png"),
  architectImg: require("./images/architect.png"),
  parkImg: require("./images/park.png"),
  mountainImg: require("./images/mountain.png"),
  chatBox: require("./images/chatBox.png"),
  findLocation: require("./images/findLocation.png"),
  predictIcon: require("./images/predict.png"),
  locationPredict: require("./images/locationPredict.png"),
  foodPredict: require("./images/foodPredict.png"),
  loadingIcon: require("./images/gif/loading.gif"),
  camera: require("./images/camera.png"),
};
